Added PAC with multi-proxy return to tests.

diff --git a/.github/workflows/ubuntu.yaml b/.github/workflows/ubuntu.yaml
--- a/.github/workflows/ubuntu.yaml
+++ b/.github/workflows/ubuntu.yaml
@@ -172,6 +172,14 @@ jobs:
           echo "Proxy for https://simple.com/ set failed"
           exit 1
         fi
+        out=$(./proxycli resolve https://multi.com/)
+        echo "Proxy for https://multi.com/: $out"
+        if [ "$out" = "http://some-such-proxy;https://secure-some-proxy:41" ]; then
+          echo "Proxy for https://multi.com/ set successfully"
+        else
+          echo "Proxy for https://multi.com/ set failed"
+          exit 1
+        fi
       working-directory: build/test
       env:
         XDG_CURRENT_DESKTOP: GNOME
