Add support for checking env settings.

diff --git a/.github/workflows/ubuntu.yaml b/.github/workflows/ubuntu.yaml
--- a/.github/workflows/ubuntu.yaml
+++ b/.github/workflows/ubuntu.yaml
@@ -39,8 +39,15 @@ jobs:
       run: ctest --verbose -C Release
       working-directory: build
 
-    - name: Dump proxy info
-      run: env | grep -i proxy
+    - name: Dump proxy info (gsettings)
+      run: |
+        gsettings get org.gnome.system.proxy autoconfig-url
+        gsettings get org.gnome.system.proxy mode
+        gsettings get org.gnome.system.proxy.http host
+        gsettings get org.gnome.system.proxy.http port
+        gsettings get org.gnome.system.proxy.https host
+        gsettings get org.gnome.system.proxy.https port
+        gsettings get org.gnome.system.proxy ignore-hosts
 
     - name: Set proxy settings (gsettings)
       run: |
@@ -98,3 +105,41 @@ jobs:
       working-directory: build/test
       env:
         XDG_CURRENT_DESKTOP: GNOME
+
+    - name: Dump proxy info (env)
+      run: env | grep -i proxy
+
+    - name: Set proxy settings (env)
+      run: |
+        echo "http_proxy=http://my.proxy2.com:8000" >> $GITHUB_ENV
+        echo "https_proxy=http://my.proxy3.com:8001" >> $GITHUB_ENV
+        echo "no_proxy=localhost,127.0.0.0/8" >> $GITHUB_ENV
+
+    - name: Check proxy settings (env)
+      shell: bash
+      run: |
+        out=$(./proxycli config proxy http)
+        echo "Proxy (http): $out"
+        if [ "$out" = "my.proxy2.com:8000" ]; then
+          echo "Proxy (http) set successfully"
+        else
+          echo "Proxy (http) set failed"
+          exit 1
+        fi
+        out=$(./proxycli config proxy https)
+        echo "Proxy (https): $out"
+        if [ "$out" = "my.proxy3.com:8001" ]; then
+          echo "Proxy (https) set successfully"
+        else
+          echo "Proxy (https) set failed"
+          exit 1
+        fi
+        out=$(./proxycli config bypass_list)
+        echo "Proxy bypass: $out"
+        if [ "$out" = "localhost,127.0.0.0/8" ]; then
+          echo "Proxy bypass set successfully"
+        else
+          echo "Proxy bypass set failed"
+          exit 1
+        fi
+      working-directory: build/test
