Added two test cases for HTTP with PROXY return value.

diff --git a/.github/workflows/ubuntu.yaml b/.github/workflows/ubuntu.yaml
--- a/.github/workflows/ubuntu.yaml
+++ b/.github/workflows/ubuntu.yaml
@@ -143,6 +143,14 @@ jobs:
           echo "Proxy for https://google.com/ set failed"
           exit 1
         fi
+        out=$(./proxycli resolve http://simple.com/)
+        echo "Proxy for http://simple.com/: $out"
+        if [ "$out" = "http://no-such-proxy:80" ]; then
+          echo "Proxy for http://simple.com/ set successfully"
+        else
+          echo "Proxy for http://simple.com/ set failed"
+          exit 1
+        fi
         out=$(./proxycli resolve https://simple.com/)
         echo "Proxy for https://simple.com/: $out"
         if [ "$out" = "https://no-such-proxy:80" ]; then
